### ISSUE TITLE
Is this expected to work with clojure 1.7+

### ISSUE THREAD

**Issue by vxe** [klutometis/reader-macros#2]
seeing the dependency of clojure 1.3 in project.clj.  Trying to track down a dependency bug when pulling in reader-macros in a different project and wanted to rule out clojure version incompatibility.

**Comment by divs1210** [comment]
Looks like this has broken. :(

**Comment by TristeFigure** [comment]
It's fixed, but pending release. See pull request https://github.com/klutometis/reader-macros/pull/8

**Comment by vxe** [comment]
🎉

**Comment by ghost** [comment]
The latest release is now available on Clojars via `[reader-macros "1.0.3"]`
