### ISSUE TITLE
cannot find 1.0.2 

### ISSUE THREAD

**Issue by JacobGood1** [klutometis/reader-macros#5]
The instructions are to use [reader-macros "1.0.2"] with lein.
However, the only version that maps to 1.0.2 on clojars is michael-reader-macros.

**Comment by michaelmrose** [comment]
Which only exists because I was trying to play with it myself and didn't know how clojars worked and you cannot remove broken things you accidentally add to clojars so sorry. I figured it was actually possible to use git repos directly in a lein project via lein-tools-deps.

**Comment by TristeFigure** [comment]
Use this version: `[org.clojars.tristefigure/reader-macros "1.0.2.1"]`

Check out https://github.com/klutometis/reader-macros/pull/6 for the details

**Comment by ghost** [comment]
The latest release is now available on Clojars via `[reader-macros "1.0.3"]`
